theme = "awesome-identity"
baseURL = "https://vanenshi.github.io"
title = "Amir Hossein Shekari - Software Engineer"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.jpeg"
  firstname = "Amir Hossein"
  lastname = "Shekari"
  title = "Software Engineer"
  bio = """Current Software Engineer at start‐up company [Mozayedegar](https://mozayedegar.ir/).

  4+ years experience specializing in back‐end and font‐end development.
  
  A person who likes to customize the development environment and adores Linux and OSX. Interested in devising a better problem‐solving method for challenging tasks, and learning new technologies and tools if the need arises.
  """

[params.contacts]
  email = "vanenshi@gmail.com"
  github = "vanenshi"
  linkedin = "vanenshi"
  stackoverflow = "8801767"

## Footer Configurations
[params.footer]
  copyright = "©2024 Amir Hossein Shekari. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
