theme = "awesome-identity"
baseURL = "https://vanenshi.com"
title = "Amir Hossein Shekari - Software Engineer"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.jpeg"
  firstname = "Amir Hossein"
  lastname = "Shekari"
  title = "Software Engineer"
  bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.

  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
  """

[params.contacts]
  email = "vanenshi@gmail.com"
  github = "vanenshi"
  linkedin = "vanenshi"
  stackoverflow = "8801767"

## Footer Configurations
[params.footer]
  copyright = "©2024 Amir Hossein Shekari. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
